### ISSUE TITLE
huggingface dataset integration readme check 

### ISSUE THREAD

**Issue by cceyda** [segments-ai/segments-ai#10]
I was following [this tutorial](https://huggingface.co/blog/fine-tune-segformer) along with my own dataset 
```py
from segments.huggingface import release2dataset

release = client.get_release(dataset_name, release_name)
hf_dataset = release2dataset(release)
```

and get file not found error because of this [line ](https://github.com/segments-ai/segments-ai/blob/9f927cb6a07fe2a0f01a3f39774b32415540eb08/segments/huggingface.py#L264)
```
with open('data/dataset_card_template.md', 'r') as f:
```

It was easy enough to create an empty "data/dataset_card_template.md" file but would be more convenient to add an file exists check  before reading the file 😄 

Awesome stuff btw !

**Comment by dbbert** [comment]
Thanks for reporting this @cceyda! We've fixed the issue in the latest release.

**Comment by dbbert** [comment]
Hi @genesismontenegro, can you upgrade to the latest version with `pip install --upgrade segments-ai` and see if that resolves the issue?
