### ISSUE TITLE
Export folder is never used

### ISSUE THREAD

**Issue by drozzy** [segments-ai/segments-ai#16]
Even though the export folder is created, it is never used, and the output still goes to `segments` folder.
https://github.com/segments-ai/segments-ai/blob/f5b3ecf2f6c50b7ead01fcfaa3af2a9db0f909ab/src/segments/export.py#L555

**Comment by dbbert** [comment]
Thanks for reporting this bug, we'll push a fix on Monday.

**Comment by dbbert** [comment]
This should now be fixed in the latest release.
