### ISSUE TITLE
KeyError: 'labelsets' when creating SegmentsDataset

### ISSUE THREAD

**Issue by anitera** [segments-ai/segments-ai#2]
Hi,
currently if I initialize dataset with code provided in google colab, I'm getting an issue. Yesterday the same code was working and some time ago instead of labelset was "task", but it seems that it changed to labelset permanently, right?
`# Initialize a dataset from the release file
release = client.get_release(dataset_name, 'v0.1')
dataset = SegmentsDataset(release, labelset='ground-truth', filter_by='labeled')`

`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-298966d8435d> in <module>()
      4 # Initialize a dataset from the release file
      5 release = client.get_release(dataset_name, 'v0.1')
----> 6 dataset = SegmentsDataset(release, labelset='ground-truth', filter_by='labeled')
      7 
      8 # Visualize a few samples in the dataset

/usr/local/lib/python3.6/dist-packages/segments/dataset.py in __init__(self, release_file, labelset, filter_by, segments_dir)
     43 
     44         # First some checks
---> 45         if not self.labelset in self.release['dataset']['labelsets']:
     46             print('There is no labelset with name "{}".'.format(self.labelset))
     47             return

KeyError: 'labelsets'`

**Comment by dbbert** [comment]
Could you try creating a new dataset release and running the code again? We have updated our SDK yesterday, and there might be compatibility issues with old release files.

Alternatively, you can install the previous version of the SDK (which should still be compatible with your old release files) with pip install segments-ai==0.22

**Comment by anitera** [comment]
Thanks, it helped. But right after those line, another error occurred. Actually, I saw 2 errors, one was that my labelset "ground-truth" not found and I tried with different labelset and than tried on tomatoes again and nowhere it worked. Next, I downgraded to segments-ai==0.22 and got "label_status" error and after I upgrade it back to 0.23 still seeing the same error.
```
# Initialize a dataset from the release file
release = client.get_release(dataset_name, 'v1.2')
dataset = SegmentsDataset(release, labelset='ground-truth', filter_by='labeled')

# Visualize a few samples in the dataset
for sample in dataset:   
    visualize(sample['image'], sample['segmentation_bitmap']) 
```


Initializing dataset. This may take a few seconds...
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-b73313aeb63c> in <module>()
      4 # Initialize a dataset from the release file
      5 release = client.get_release(dataset_name, 'v1.2')
----> 6 dataset = SegmentsDataset(release, labelset='ground-truth', filter_by='labeled')
      7 
      8 # Visualize a few samples in the dataset

1 frames
/usr/local/lib/python3.6/dist-packages/segments/dataset.py in load_dataset(self)
     57             for sample in samples:
     58                 if sample['labels'][self.task] is not None:
---> 59                     label_status = sample['labels'][self.task]['label_status'].lower()
     60                 else:
     61                     label_status = 'unlabeled'

KeyError: 'label_status'

**Comment by dbbert** [comment]
You're right, there was another bug I overlooked, apologies! Could you update the SDK (pip install --upgrade segmentsai), create a new release, and try again?

**Comment by anitera** [comment]
No worry :)
well, for some reason I can't. Both upgrade or reinstalling throw: 
"ERROR: Could not find a version that satisfies the requirement segmentsai (from versions: none)
ERROR: No matching distribution found for segmentsai"

**Comment by dbbert** [comment]
Sorry I made a typo, that should've been `pip install --upgrade segments-ai`, with a dash.

**Comment by anitera** [comment]
Thanks, now it's working and I managed to upload new predictions.
