### ISSUE TITLE
Release files - Enhancement request 

### ISSUE THREAD

**Issue by ssnirgudkar** [segments-ai/segments-ai#3]
Hi Bert, 

Today, the release files are more for export. However, I think it will help if the release files can also drive the creation of samples, modification of already existing work. For eg - 
1. I complete my labeling with 5 classes - Release 1. Then decide to add another class on top. I could create my labeled samples dataset using Release 1 (in a different folder) and then start from there, making modifications to each image for the newly added class on top of the segmentation that already exists. 
2. Or I want to revisit and make finer adjustments as new scenarios come across. So each release is not just a representation of the pixel value but carries with it the class json file - so a complete unit that I can use to recreate that release as is - with it's classes, and the segmentation built using those classes. 

Currently, when I delete a release and go back to the older one, the class file (setting) is still retained as the latest one and the samples point back to that file. Instead, each delete of release can wipe out the class json/setting file, and revert that to the one that corresponds to the active release. Basically the release file should have a one to one match with the setting file (like git). 

I understand that despite the setting file being retained, the segmentation stays - so all objects are mapped, it's just that i need to re-apply the labels. But I believe above feature will be helpful in saving time, or being able to create multiple folders by uploading a release instead of only samples. 

Let me know what you think, 
Shailesh

**Comment by dbbert** [comment]
Hi Shailesh, seems like I missed this issue when you posted it a while ago, apologies! I'm closing it but will give it some thought and get back to you via email.
