### ISSUE TITLE
release2dataset throws an error

### ISSUE THREAD

**Issue by v-prgmr** [segments-ai/segments-ai#60]
Hi

I created a dataset using the webinterface and finally converting the dataset to hf format using release2dataset throws the following error.

Code:
```segments_client = SegmentsClient('########')
release = segments_client.get_release("###/###", "v0.1")
hf_dataset = release2dataset(release)```


Error:
`  File "pyarrow\table.pxi", line 3315, in pyarrow.lib.Table.combine_chunks
  File "pyarrow\error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: offset overflow while concatenating arrays`

**Comment by v-prgmr** [comment]
@segments-arnaud after an intuition that may be the image file size is too big, I reduced the resolution by 25% and was finally able to pack the segments.ai dataset into a hfdataset. But now I face another issue where while pulling the dataset for fine tuning a segformer, at the start of the training loop, I get the following error as mentioned in https://github.com/segments-ai/segments-ai/issues/62#issue-1630320089

**Comment by dbbert** [comment]
Closing in favor of #62

**Comment by SalmaHisham** [comment]
@v-prgmr 
Hi, could you please tell me how you could reduce the resolution by 25% after the annotation step creating the release?
I am stuck on the same issue.
