### ISSUE TITLE
no json file for huggingface dataset

### ISSUE THREAD

**Issue by Yiiii19** [segments-ai/segments-ai#61]
Hi,
I am using this tool for generating custom dataset. However, after release i cannot find the corresponding "id2label.json" file. Is that possible automatically to generate? Thanks.
Example:
{"0": "unlabeled", "1": "flat-road"}

**Comment by segments-tobias** [comment]
@Yiiii19 What version of the Python SDK are you using? If you're using a version before 1.0.17, you'll have to upgrade the SDK using `pip install segments-ai --upgrade`

**Comment by v-prgmr** [comment]
@segments-tobias  I have 1.0.21 and still the json file does not get created after pushing to HF

**Comment by dbbert** [comment]
Hi @v-prgmr I tried reproducing this issue with the latest versions of `segments-ai` (1.0.21) and `datasets` (2.11.0) but the `id2label.json` file gets created just fine for me.

Are you getting an error or warning message of any kind? Could you point me to the dataset on Segments.ai which you're trying to export to HF?

**Comment by dbbert** [comment]
Also when exporting this dataset the `id2label.json` file gets created for me, see screenshot. Can you confirm you're on the latest `datasets` version?

![image](https://user-images.githubusercontent.com/3367974/234249246-f22074c3-51d6-449f-b93e-44cea95518a6.png)

This is the code I'm running:
```
from segments import SegmentsClient
from segments.huggingface import release2dataset

client = SegmentsClient("YOUR_API_KEY")
release = client.get_release("xorder/xorder_205", "v0.1")

dataset = release2dataset(release, True)
dataset.push_to_hub("segments-bert/xorder", private=True)
```
