### ISSUE TITLE
access labeler for a given sample or annotation

### ISSUE THREAD

**Issue by Gijs-Koot** [segments-ai/segments-ai#7]
Hi, I'm looking for a way to know the user that submitted a particular annotation or sample. I tried figuring this out from the examples in the API docs, but I couldn't quite find the information I'm looking for. Is there a way to obtain a username or userid for an annotation through the API?

**Comment by dbbert** [comment]
Assuming you're using the Python SDK, the [`get_label()`](https://docs.segments.ai/reference/python-sdk#get-a-label) function returns both the username of the labeler (`created_by`) and the reviewer (`reviewed_by`).

Note that you can also get the sample and label in one call with [`get_sample()`](https://docs.segments.ai/reference/python-sdk#get-a-sample), by providing the additional `labelset` argument to the function call.

The return values of the Python SDK function calls are not well documented at the moment, this is something we're working on improving in the short term!
