### ISSUE TITLE
Export dataset error 

### ISSUE THREAD

**Issue by Zaherkorechi** [segments-ai/segments-ai#8]
Some of the images in our dataset has orientation error, where those images has ExifTags for fix the orientation.

```
from PIL import Image, ExifTags
import numpy as np

try:

    for orientation in ExifTags.TAGS.keys():
              if ExifTags.TAGS[orientation]=='Orientation':
                  break

    for i,sample in enumerate(labeled_dataset):

      if(np.asarray(sample['image']).shape[:2] != np.asarray(sample['segmentation_bitmap']).shape[:2]):
        print("old ",sample['name'],np.asarray(sample['image']).shape)

        image_path = "/content/fast-labeling-workflow/segments/Sougata_Apple_Train/v0.3/"+sample['name'].split(".")[0]+".jpg"
        print(image_path)
        image=Image.open(image_path)
      
        
        exif=dict(image._getexif().items())

        if exif[orientation] == 3:
            image=image.transpose(Image.ROTATE_180)
        elif exif[orientation] == 6:
            image=image.transpose(Image.ROTATE_270)
        elif exif[orientation] == 8:
            image=image.transpose(Image.ROTATE_90)
        print("New ",np.asarray(image).shape)

except (AttributeError, KeyError, IndexError) as e:
    # cases: image don't have getexif
    print(e)
    pass
```

When I upload the image from my machine that code work fine, but when I download the date by using Python SDK, the image is downloaded without any attributes I am getting this error:
```
old  GOPR2236.JPG (3000, 4000, 3)
/content/fast-labeling-workflow/segments/Sougata_Apple_Train/v0.3/GOPR2236.jpg
'NoneType' object has no attribute 'items'
```

So, is there a way to download the data with EXIF attributes.

**Comment by dbbert** [comment]
This was indeed a bug on our end: when creating a `SegmentsDataset()` the images are downloaded and saved to the cache directory, but apparently their EXIF data was not retained at this point. I've now pushed a fix for this. 

Can you try again after upgrading with `pip install --upgrade segments-ai`? You'll also have to delete the segments cache directory (`/content/fast-labeling-workflow/segments/`) for the changes to take effect.
