### ISSUE TITLE
error when loading dataset with image with no segmentation mask

### ISSUE THREAD

**Issue by stevensagaert** [segments-ai/segments-ai#84]
in the pfizer dataset there are images where the url for the segmentation mask is None. This gives an error when loading the dataset and stops further loading.

I fixed this as follows: in dataset.py  from line 268 onwards

if not os.path.exists(segmentation_bitmap_filename):
                if segmentation_bitmap_url is not None:
                    return load_label_bitmap_from_url(
                        segmentation_bitmap_url, segmentation_bitmap_filename
                    )
            else:
                return Image.open(segmentation_bitmap_filename)

**Comment by dbbert** [comment]
Are you on the latest version of the Python SDK? Can you share (privately to bert@segments.ai) for which dataset and release you're encountering this issue?

There is actually [some code](https://github.com/segments-ai/segments-ai/blob/86534baaef451fcb3ab907f7578e23fa371db2cf/src/segments/dataset.py#L344) in place to catch this scenario but maybe we have a bug in there. If so, we'll add your fix in the next SDK release.

**Comment by stevensagaert** [comment]
Yes this is on the latest version of the SDK. The dataset is https://segments.ai/pfizer/farad2sort-v3/
________________________________

**Comment by dbbert** [comment]
Ok this looks to be an edge case because the dataset contains pre-labeled samples for which the `segmentation_bitmap` key is set but the `url` sub-field is left empty. We'll add your fix in the next SDK release to handle this.
