### ISSUE TITLE
the documentation for the python SDK should mention the minimum supported python version per release

### ISSUE THREAD

**Issue by stevensagaert** [segments-ai/segments-ai#85]
Problem:
the last SDK release does not work with python 3.8.10 (the python version of Ubuntu 20.04) due to errors from typing/pydantic. This should be documented.

**Comment by segments-arnaud** [comment]
Which error do you get?

**Comment by stevensagaert** [comment]
schema error. because requests lib is trying to load a url None
________________________________

**Comment by segments-arnaud** [comment]
Can you check if you're using pydantic v2 and if so if does downgrading to pydantic v1 solve the issue?

**Comment by stevensagaert** [comment]
these are the warnings I get when the script is started:

/home/steven.sagaert/miniconda3/envs/faradserver/lib/python3.8/site-packages/pydantic/_internal/_config.py:261: UserWarning: Valid config keys have changed in V2:
* 'smart_union' has been removed
  warnings.warn(message, UserWarning)
/home/steven.sagaert/miniconda3/envs/faradserver/lib/python3.8/site-packages/pydantic/_internal/_config.py:261: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
/home/steven.sagaert/miniconda3/envs/faradserver/lib/python3.8/site-packages/pydantic/_internal/_config.py:261: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'smart_union' has been removed
  warnings.warn(message, UserWarning)

this is the error I get later on:
uploading priorities
  0%|                                                                                                                                                              | 0/4434 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/steven.sagaert/miniconda3/envs/faradserver/lib/python3.8/site-packages/segments/client.py", line 105, in throw_segments_exception
    m = parse_obj_as(model, r_json)
  File "/home/steven.sagaert/miniconda3/envs/faradserver/lib/python3.8/site-packages/typing_extensions.py", line 2562, in wrapper
    return __arg(*args, **kwargs)
  File "/home/steven.sagaert/miniconda3/envs/faradserver/lib/python3.8/site-packages/pydantic/deprecated/tools.py", line 41, in parse_obj_as
    return TypeAdapter(type_).validate_python(obj)
  File "/home/steven.sagaert/miniconda3/envs/faradserver/lib/python3.8/site-packages/pydantic/type_adapter.py", line 206, in validate_python
    return self.validator.validate_python(__object, strict=strict, from_attributes=from_attributes, context=context)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Sample
label
  Field required [type=missing, input_value={'uuid': 'd06c918b-321d-4... 'pfizer/farad2sort-v3'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.3/v/missing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/steven.sagaert/python_workspace/FARAD2SORT/FARAD_research/Steven/Active/initial_training.py", line 132, in <module>
    update_priorities(dataset, priorities) #this is slow! could speed it via multithreading (see download code).
  File "/home/steven.sagaert/python_workspace/FARAD2SORT/FARAD_research/Steven/Active/segments_interface.py", line 101, in update_priorities
    client.update_sample(uuid, priority=float(priority_dict[name])) #Note float() is necessary to convert numpy.float32 to float64 because the python json lib does NOT support float32!
  File "/home/steven.sagaert/miniconda3/envs/faradserver/lib/python3.8/site-packages/segments/client.py", line 1072, in update_sample
    r = self._patch(f"/samples/{uuid}/", data=payload, model=Sample)
  File "/home/steven.sagaert/miniconda3/envs/faradserver/lib/python3.8/site-packages/segments/client.py", line 141, in throw_segments_exception
    raise ValidationError(message=str(e), cause=e)
segments.exceptions.ValidationError: 1 validation error for Sample
label
  Field required [type=missing, input_value={'uuid': 'd06c918b-321d-4... 'pfizer/farad2sort-v3'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.3/v/missing
Validation Errors - Pydantic<https://errors.pydantic.dev/2.0.3/v/missing>
Data validation using Python type hints
errors.pydantic.dev

________________________________

**Comment by segments-arnaud** [comment]
Thanks! It seems you're on Pydantic V2. Can you run `pip install 'pydantic<2'` in the terminal and check if this solves it.

**Comment by segments-arnaud** [comment]
Great. No this is a bug in our requirements file (independent of Python version). I will push a fix that sets the package versions to prevent this issue in the future! Thanks.
