### ISSUE TITLE
pycocotools is a problematic dependency

### ISSUE THREAD

**Issue by Gijs-Koot** [segments-ai/segments-ai#9]
Hi. I'm wondering if it is possible to make `pycocotools` an optional dependency. As far as I can tell, this dependency is used in `export.py` - it's use is even a bit suspect as the import is `from pycocotools import mask`, but then the script uses a variable `mask` as well, which - excuse me - _masks_ the import. 

The issue is that `pycocotools` is a problematic package to install, it gives all kinds of problems and is not maintained at all. Given it's limited use here, might it be possible to either make this package optional to install, or even remove the whole dependency? 

I could make a PR as well if you like, let me know.

**Comment by dbbert** [comment]
Good points, thanks Gijs. I've pushed a new version where the dependency on `pycocotools` is removed and made optional. Also fixed the `mask` naming conflict.

**Comment by Gijs-Koot** [comment]
Great @dbbert!
